### ISSUE TITLE
Temp File error when running on windows

### ISSUE THREAD

**Issue by yashrs** [MilindPurswani/Syborg#6]
Sample error:

```
PS > python .\syborg.py domain.com
Traceback (most recent call last):
  File ".\syborg.py", line 174, in <module>
    q = filequeue.FileQueue(maxsize=1000)
  File "C:\Python36\lib\site-packages\filequeue\filequeue.py", line 53, in __init__
    self._init_fds()
  File "C:\Python36\lib\site-packages\filequeue\filequeue.py", line 56, in _init_fds
    self._file_write = _file_open(self._temp_file.name, "wb")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Yash\\AppData\\Local\\Temp\\tmpqnp_lbdw.queue'
```

**Comment by MilindPurswani** [comment]
Seems like this error is raised by `FileQueue` library in windows. Will check it out. Thanks for bringing it in. 👍

**Comment by MilindPurswani** [comment]
Referenced at [FileQueue](https://github.com/GP89/FileQueue/issues/5/)

**Comment by GP89** [comment]
This should now be fixed in `filequeue` 0.4.0 👍

**Comment by MilindPurswani** [comment]
@yashrs can you kindly check and confirm the fix? 

Thanks, 

-Milind

**Comment by MilindPurswani** [comment]
Seems to be resolved now. Closing it.
